# -*- coding: utf-8 -*-
"""Sales Predection.ipyn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6cREKOFD_3QnJqrjqKgxz6JSGZjis1a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df=pd.read_csv("Advertising.csv")
df

df=df.drop(columns="ID")
df

df.info()

df.columns

df.isnull().sum()

df.describe()

df.corr

df.nunique()

plt.figure(figsize=(10,10))
df.boxplot()

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(12,10))
sns.heatmap(df.corr())
plt.show()

sns.pairplot(df, size=5)

x=np.array(df.drop(["Sales"],1))
y=np.array(df["Sales"])
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.20, random_state=0)
#aprint(message.shape)
model=LinearRegression()
model.fit(xtrain,ytrain)
ypread=model.predict(xtest)
data=pd.DataFrame(data={"Predicated sales":ypread.flatten()})
print(data)

